#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Wed Oct 06 16:46:03 CEST 2021
# SW Build 3064766 on Wed Nov 18 09:12:47 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# elaborate design
echo "xelab -wto ff26f8deab6d4604954c61f33827ef35 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot tb_AXI4Stream_X7S_VirtualTDLWrapper_behav xil_defaultlib.tb_AXI4Stream_X7S_VirtualTDLWrapper -log elaborate.log"
xelab -wto ff26f8deab6d4604954c61f33827ef35 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot tb_AXI4Stream_X7S_VirtualTDLWrapper_behav xil_defaultlib.tb_AXI4Stream_X7S_VirtualTDLWrapper -log elaborate.log

