# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/top_bd/top_bd.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_bd || ORIG_REF_NAME==top_bd} -quiet] -quiet

# IP: bd/top_bd/ip/top_bd_axi_uartlite_0_0/top_bd_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_bd_axi_uartlite_0_0 || ORIG_REF_NAME==top_bd_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/top_bd/ip/top_bd_clk_wiz_0_0/top_bd_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_bd_clk_wiz_0_0 || ORIG_REF_NAME==top_bd_clk_wiz_0_0} -quiet] -quiet

# IP: bd/top_bd/ip/top_bd_axi4_counter_0_0/top_bd_axi4_counter_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_bd_axi4_counter_0_0 || ORIG_REF_NAME==top_bd_axi4_counter_0_0} -quiet] -quiet

# IP: bd/top_bd/ip/top_bd_system_ila_0_0/top_bd_system_ila_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_bd_system_ila_0_0 || ORIG_REF_NAME==top_bd_system_ila_0_0} -quiet] -quiet

# IP: bd/top_bd/ip/top_bd_proc_sys_reset_0_0/top_bd_proc_sys_reset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_bd_proc_sys_reset_0_0 || ORIG_REF_NAME==top_bd_proc_sys_reset_0_0} -quiet] -quiet

# XDC: bd/top_bd/top_bd_ooc.xdc
