# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/DESD/Projects/LAB3__Exercise__Solution.xpr/LAB3/LAB3.srcs/sources_1/bd/top_bd/ip/top_bd_AXI4Stream_UART_0_1/top_bd_AXI4Stream_UART_0_1.xci
# IP: The module: 'top_bd_AXI4Stream_UART_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/DESD/Projects/LAB3__Exercise__Solution.xpr/LAB3/LAB3.srcs/sources_1/bd/top_bd/ip/top_bd_AXI4Stream_UART_0_1/top_bd_AXI4Stream_UART_0_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_bd_AXI4Stream_UART_0_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/DESD/Projects/LAB3__Exercise__Solution.xpr/LAB3/LAB3.srcs/sources_1/bd/top_bd/ip/top_bd_AXI4Stream_UART_0_1/top_bd_AXI4Stream_UART_0_1.xci
# IP: The module: 'top_bd_AXI4Stream_UART_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/DESD/Projects/LAB3__Exercise__Solution.xpr/LAB3/LAB3.srcs/sources_1/bd/top_bd/ip/top_bd_AXI4Stream_UART_0_1/top_bd_AXI4Stream_UART_0_1_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_bd_AXI4Stream_UART_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
