# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/DESD/audio_project/audio_project.srcs/sources_1/bd/audio_bd/ip/audio_bd_clk_wiz_0_0/audio_bd_clk_wiz_0_0.xci
# IP: The module: 'audio_bd_clk_wiz_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/DESD/audio_project/audio_project.gen/sources_1/bd/audio_bd/ip/audio_bd_clk_wiz_0_0/audio_bd_clk_wiz_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'audio_bd_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/DESD/audio_project/audio_project.gen/sources_1/bd/audio_bd/ip/audio_bd_clk_wiz_0_0/audio_bd_clk_wiz_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'audio_bd_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/DESD/audio_project/audio_project.gen/sources_1/bd/audio_bd/ip/audio_bd_clk_wiz_0_0/audio_bd_clk_wiz_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'audio_bd_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/DESD/audio_project/audio_project.srcs/sources_1/bd/audio_bd/ip/audio_bd_clk_wiz_0_0/audio_bd_clk_wiz_0_0.xci
# IP: The module: 'audio_bd_clk_wiz_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/DESD/audio_project/audio_project.gen/sources_1/bd/audio_bd/ip/audio_bd_clk_wiz_0_0/audio_bd_clk_wiz_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'audio_bd_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/DESD/audio_project/audio_project.gen/sources_1/bd/audio_bd/ip/audio_bd_clk_wiz_0_0/audio_bd_clk_wiz_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'audio_bd_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/DESD/audio_project/audio_project.gen/sources_1/bd/audio_bd/ip/audio_bd_clk_wiz_0_0/audio_bd_clk_wiz_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'audio_bd_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
