# Pin assignment for the Pmod-I2S2 module on the JB Pmod connector of the Basys 3 board
set_property IOSTANDARD LVCMOS33 [get_ports rx_lrck_0]
set_property IOSTANDARD LVCMOS33 [get_ports rx_mclk_0]
set_property IOSTANDARD LVCMOS33 [get_ports rx_sclk_0]
set_property IOSTANDARD LVCMOS33 [get_ports rx_sdin_0]
set_property IOSTANDARD LVCMOS33 [get_ports tx_lrck_0]
set_property IOSTANDARD LVCMOS33 [get_ports tx_mclk_0]
set_property IOSTANDARD LVCMOS33 [get_ports tx_sclk_0]
set_property IOSTANDARD LVCMOS33 [get_ports tx_sdout_0]
set_property PACKAGE_PIN A14 [get_ports tx_mclk_0]
set_property PACKAGE_PIN A16 [get_ports tx_lrck_0]
set_property PACKAGE_PIN B15 [get_ports tx_sclk_0]
set_property PACKAGE_PIN B16 [get_ports tx_sdout_0]
set_property PACKAGE_PIN A15 [get_ports rx_mclk_0]
set_property PACKAGE_PIN A17 [get_ports rx_lrck_0]
set_property PACKAGE_PIN C15 [get_ports rx_sclk_0]
set_property PACKAGE_PIN C16 [get_ports rx_sdin_0]

# Pin assignment for the Pmod-JSTK2 module on the JA Pmod connector of the Basys 3 board
set_property IOSTANDARD LVCMOS33 [get_ports {SPI_0_ss_io[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports SPI_0_io0_io]
set_property IOSTANDARD LVCMOS33 [get_ports SPI_0_io1_io]
set_property IOSTANDARD LVCMOS33 [get_ports SPI_0_sck_io]
set_property PACKAGE_PIN J1 [get_ports {SPI_0_ss_io[0]}]
set_property PACKAGE_PIN L2 [get_ports SPI_0_io0_io]
set_property PACKAGE_PIN J2 [get_ports SPI_0_io1_io]
set_property PACKAGE_PIN G2 [get_ports SPI_0_sck_io]

set_property IOSTANDARD LVCMOS33 [get_ports input_signal_0]
set_property PACKAGE_PIN T18 [get_ports input_signal_0]
set_property PACKAGE_PIN U17 [get_ports input_signal_1]
set_property IOSTANDARD LVCMOS33 [get_ports input_signal_1]
