# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/DESD/PW/Audio/Audio/VHDL/VHDL/Basys3_Constraints.xdc

# Block Designs: bd/audio_bd/audio_bd.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==audio_bd || ORIG_REF_NAME==audio_bd} -quiet] -quiet

# IP: bd/audio_bd/ip/audio_bd_pmod_i2s2_0_0/audio_bd_pmod_i2s2_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==audio_bd_pmod_i2s2_0_0 || ORIG_REF_NAME==audio_bd_pmod_i2s2_0_0} -quiet] -quiet

# IP: bd/audio_bd/ip/audio_bd_clk_wiz_0_0/audio_bd_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==audio_bd_clk_wiz_0_0 || ORIG_REF_NAME==audio_bd_clk_wiz_0_0} -quiet] -quiet

# IP: bd/audio_bd/ip/audio_bd_util_vector_logic_0_0/audio_bd_util_vector_logic_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==audio_bd_util_vector_logic_0_0 || ORIG_REF_NAME==audio_bd_util_vector_logic_0_0} -quiet] -quiet

# IP: bd/audio_bd/ip/audio_bd_Pmod_JSTK2_0_0/audio_bd_Pmod_JSTK2_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==audio_bd_Pmod_JSTK2_0_0 || ORIG_REF_NAME==audio_bd_Pmod_JSTK2_0_0} -quiet] -quiet

# IP: bd/audio_bd/ip/audio_bd_moving_average_0_0/audio_bd_moving_average_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==audio_bd_moving_average_0_0 || ORIG_REF_NAME==audio_bd_moving_average_0_0} -quiet] -quiet

# IP: bd/audio_bd/ip/audio_bd_debouncer_0_0/audio_bd_debouncer_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==audio_bd_debouncer_0_0 || ORIG_REF_NAME==audio_bd_debouncer_0_0} -quiet] -quiet

# IP: bd/audio_bd/ip/audio_bd_debouncer_1_0/audio_bd_debouncer_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==audio_bd_debouncer_1_0 || ORIG_REF_NAME==audio_bd_debouncer_1_0} -quiet] -quiet

# IP: bd/audio_bd/ip/audio_bd_edge_detector_0_0/audio_bd_edge_detector_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==audio_bd_edge_detector_0_0 || ORIG_REF_NAME==audio_bd_edge_detector_0_0} -quiet] -quiet

# IP: bd/audio_bd/ip/audio_bd_edge_detector_1_0/audio_bd_edge_detector_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==audio_bd_edge_detector_1_0 || ORIG_REF_NAME==audio_bd_edge_detector_1_0} -quiet] -quiet

# IP: bd/audio_bd/ip/audio_bd_mute_controller_0_0/audio_bd_mute_controller_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==audio_bd_mute_controller_0_0 || ORIG_REF_NAME==audio_bd_mute_controller_0_0} -quiet] -quiet

# IP: bd/audio_bd/ip/audio_bd_LED_controller_0_0/audio_bd_LED_controller_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==audio_bd_LED_controller_0_0 || ORIG_REF_NAME==audio_bd_LED_controller_0_0} -quiet] -quiet

# IP: bd/audio_bd/ip/audio_bd_volume_controller_0_0/audio_bd_volume_controller_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==audio_bd_volume_controller_0_0 || ORIG_REF_NAME==audio_bd_volume_controller_0_0} -quiet] -quiet

# IP: bd/audio_bd/ip/audio_bd_audio_balance_0_0/audio_bd_audio_balance_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==audio_bd_audio_balance_0_0 || ORIG_REF_NAME==audio_bd_audio_balance_0_0} -quiet] -quiet

# XDC: c:/DESD/audio_project/audio_project.gen/sources_1/bd/audio_bd/audio_bd_ooc.xdc
