# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/new/basys3_master_xdc.xdc

# Block Designs: bd/design_1/design_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_depacketizer_0_0/design_1_depacketizer_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_depacketizer_0_0 || ORIG_REF_NAME==design_1_depacketizer_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_AXI4Stream_UART_0_0/design_1_AXI4Stream_UART_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_AXI4Stream_UART_0_0 || ORIG_REF_NAME==design_1_AXI4Stream_UART_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_0_0 || ORIG_REF_NAME==design_1_clk_wiz_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_util_vector_logic_0_0/design_1_util_vector_logic_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_util_vector_logic_0_0 || ORIG_REF_NAME==design_1_util_vector_logic_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_packetizer_0_0/design_1_packetizer_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_packetizer_0_0 || ORIG_REF_NAME==design_1_packetizer_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_moving_average_filter_0_0/design_1_moving_average_filter_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_moving_average_filter_0_0 || ORIG_REF_NAME==design_1_moving_average_filter_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_volume_controller_1_0/design_1_volume_controller_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_volume_controller_1_0 || ORIG_REF_NAME==design_1_volume_controller_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_mute_controller_0_0/design_1_mute_controller_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_mute_controller_0_0 || ORIG_REF_NAME==design_1_mute_controller_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_debouncer_0_0/design_1_debouncer_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_debouncer_0_0 || ORIG_REF_NAME==design_1_debouncer_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_debouncer_1_0/design_1_debouncer_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_debouncer_1_0 || ORIG_REF_NAME==design_1_debouncer_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_edge_detector_0_0/design_1_edge_detector_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_edge_detector_0_0 || ORIG_REF_NAME==design_1_edge_detector_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_edge_detector_1_0/design_1_edge_detector_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_edge_detector_1_0 || ORIG_REF_NAME==design_1_edge_detector_1_0} -quiet] -quiet

# XDC: bd/design_1/design_1_ooc.xdc
