# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/top_bd/top_bd.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_bd || ORIG_REF_NAME==top_bd} -quiet] -quiet

# IP: bd/top_bd/ip/top_bd_clk_wiz_0_0/top_bd_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_bd_clk_wiz_0_0 || ORIG_REF_NAME==top_bd_clk_wiz_0_0} -quiet] -quiet

# IP: bd/top_bd/ip/top_bd_util_vector_logic_0_0/top_bd_util_vector_logic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_bd_util_vector_logic_0_0 || ORIG_REF_NAME==top_bd_util_vector_logic_0_0} -quiet] -quiet

# IP: bd/top_bd/ip/top_bd_depacketizer_0_0/top_bd_depacketizer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_bd_depacketizer_0_0 || ORIG_REF_NAME==top_bd_depacketizer_0_0} -quiet] -quiet

# IP: bd/top_bd/ip/top_bd_packetizer_0_0/top_bd_packetizer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_bd_packetizer_0_0 || ORIG_REF_NAME==top_bd_packetizer_0_0} -quiet] -quiet

# IP: bd/top_bd/ip/top_bd_AXI4Stream_UART_0_1/top_bd_AXI4Stream_UART_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==top_bd_AXI4Stream_UART_0_1 || ORIG_REF_NAME==top_bd_AXI4Stream_UART_0_1} -quiet] -quiet

# XDC: bd/top_bd/top_bd_ooc.xdc
