# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/DESD/Projects/LAB2__HomeAssigmement__Solution/color_to_grayscale.xpr/color_to_grayscale/color_to_grayscale.srcs/sources_1/bd/top_bd/ip/top_bd_clk_wiz_0_0/top_bd_clk_wiz_0_0.xci
# IP: The module: 'top_bd_clk_wiz_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/DESD/Projects/LAB2__HomeAssigmement__Solution/color_to_grayscale.xpr/color_to_grayscale/color_to_grayscale.srcs/sources_1/bd/top_bd/ip/top_bd_clk_wiz_0_0/top_bd_clk_wiz_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_bd_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/DESD/Projects/LAB2__HomeAssigmement__Solution/color_to_grayscale.xpr/color_to_grayscale/color_to_grayscale.srcs/sources_1/bd/top_bd/ip/top_bd_clk_wiz_0_0/top_bd_clk_wiz_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_bd_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/DESD/Projects/LAB2__HomeAssigmement__Solution/color_to_grayscale.xpr/color_to_grayscale/color_to_grayscale.srcs/sources_1/bd/top_bd/ip/top_bd_clk_wiz_0_0/top_bd_clk_wiz_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_bd_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/DESD/Projects/LAB2__HomeAssigmement__Solution/color_to_grayscale.xpr/color_to_grayscale/color_to_grayscale.srcs/sources_1/bd/top_bd/ip/top_bd_clk_wiz_0_0/top_bd_clk_wiz_0_0.xci
# IP: The module: 'top_bd_clk_wiz_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/DESD/Projects/LAB2__HomeAssigmement__Solution/color_to_grayscale.xpr/color_to_grayscale/color_to_grayscale.srcs/sources_1/bd/top_bd/ip/top_bd_clk_wiz_0_0/top_bd_clk_wiz_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_bd_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/DESD/Projects/LAB2__HomeAssigmement__Solution/color_to_grayscale.xpr/color_to_grayscale/color_to_grayscale.srcs/sources_1/bd/top_bd/ip/top_bd_clk_wiz_0_0/top_bd_clk_wiz_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_bd_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/DESD/Projects/LAB2__HomeAssigmement__Solution/color_to_grayscale.xpr/color_to_grayscale/color_to_grayscale.srcs/sources_1/bd/top_bd/ip/top_bd_clk_wiz_0_0/top_bd_clk_wiz_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_bd_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
