# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/DESD/shooter_project/shooter_project.srcs/sources_1/ip/AXI4Stream_RS232_0/AXI4Stream_RS232_0.xci
# IP: The module: 'AXI4Stream_RS232_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/DESD/shooter_project/shooter_project.gen/sources_1/ip/AXI4Stream_RS232_0/AXI4Stream_RS232_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'AXI4Stream_RS232_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/DESD/shooter_project/shooter_project.srcs/sources_1/ip/AXI4Stream_RS232_0/AXI4Stream_RS232_0.xci
# IP: The module: 'AXI4Stream_RS232_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/DESD/shooter_project/shooter_project.gen/sources_1/ip/AXI4Stream_RS232_0/AXI4Stream_RS232_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'AXI4Stream_RS232_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
