set_property MARK_DEBUG true [get_nets s00_axis_tx_tready]
set_property MARK_DEBUG true [get_nets {m00_axis_rx_tdata[1]}]
set_property MARK_DEBUG true [get_nets {m00_axis_rx_tdata[0]}]
set_property MARK_DEBUG true [get_nets {m00_axis_rx_tdata[2]}]
set_property MARK_DEBUG true [get_nets {m00_axis_rx_tdata[3]}]
set_property MARK_DEBUG true [get_nets {m00_axis_rx_tdata[4]}]
set_property MARK_DEBUG true [get_nets {m00_axis_rx_tdata[5]}]
set_property MARK_DEBUG true [get_nets {m00_axis_rx_tdata[7]}]
set_property MARK_DEBUG true [get_nets s00_axis_tx_tvalid]
set_property MARK_DEBUG true [get_nets {s00_axis_tx_tdata[0]}]
set_property MARK_DEBUG true [get_nets {m00_axis_rx_tdata[6]}]
set_property MARK_DEBUG true [get_nets {s00_axis_tx_tdata[1]}]
set_property MARK_DEBUG true [get_nets {s00_axis_tx_tdata[2]}]
set_property MARK_DEBUG true [get_nets {s00_axis_tx_tdata[3]}]
set_property MARK_DEBUG true [get_nets {s00_axis_tx_tdata[4]}]
set_property MARK_DEBUG true [get_nets {s00_axis_tx_tdata[5]}]
set_property MARK_DEBUG true [get_nets {s00_axis_tx_tdata[6]}]
set_property MARK_DEBUG true [get_nets {s00_axis_tx_tdata[7]}]
set_property MARK_DEBUG true [get_nets m00_axis_rx_tready]
set_property MARK_DEBUG true [get_nets m00_axis_rx_tvalid]

create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list clk_IBUF_BUFG]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 8 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {s00_axis_tx_tdata[0]} {s00_axis_tx_tdata[1]} {s00_axis_tx_tdata[2]} {s00_axis_tx_tdata[3]} {s00_axis_tx_tdata[4]} {s00_axis_tx_tdata[5]} {s00_axis_tx_tdata[6]} {s00_axis_tx_tdata[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 8 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {m00_axis_rx_tdata[0]} {m00_axis_rx_tdata[1]} {m00_axis_rx_tdata[2]} {m00_axis_rx_tdata[3]} {m00_axis_rx_tdata[4]} {m00_axis_rx_tdata[5]} {m00_axis_rx_tdata[6]} {m00_axis_rx_tdata[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 1 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list m00_axis_rx_tready]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 1 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list m00_axis_rx_tvalid]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 1 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list s00_axis_tx_tready]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 1 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list s00_axis_tx_tvalid]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk_IBUF_BUFG]
