# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/DESD/shooter_project/shooter_project.srcs/sources_1/ip/Pmod_JSTK2_0/Pmod_JSTK2_0.xci
# IP: The module: 'Pmod_JSTK2_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/DESD/shooter_project/shooter_project.gen/sources_1/ip/Pmod_JSTK2_0/src/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_0_0 || ORIG_REF_NAME==design_1_clk_wiz_0_0} -quiet] -quiet

# IP: c:/DESD/shooter_project/shooter_project.gen/sources_1/ip/Pmod_JSTK2_0/src/design_1_proc_sys_reset_0_0/design_1_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_proc_sys_reset_0_0 || ORIG_REF_NAME==design_1_proc_sys_reset_0_0} -quiet] -quiet

# IP: c:/DESD/shooter_project/shooter_project.gen/sources_1/ip/Pmod_JSTK2_0/src/design_1_axi_quad_spi_0_0/design_1_axi_quad_spi_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_quad_spi_0_0 || ORIG_REF_NAME==design_1_axi_quad_spi_0_0} -quiet] -quiet

# XDC: c:/DESD/shooter_project/shooter_project.gen/sources_1/ip/Pmod_JSTK2_0/src/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_0_0 || ORIG_REF_NAME==design_1_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/DESD/shooter_project/shooter_project.gen/sources_1/ip/Pmod_JSTK2_0/src/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0_ooc.xdc

# XDC: c:/DESD/shooter_project/shooter_project.gen/sources_1/ip/Pmod_JSTK2_0/src/design_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Pmod_JSTK2_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/DESD/shooter_project/shooter_project.gen/sources_1/ip/Pmod_JSTK2_0/src/design_1_proc_sys_reset_0_0/design_1_proc_sys_reset_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_proc_sys_reset_0_0 || ORIG_REF_NAME==design_1_proc_sys_reset_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/DESD/shooter_project/shooter_project.gen/sources_1/ip/Pmod_JSTK2_0/src/design_1_axi_quad_spi_0_0/design_1_axi_quad_spi_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_axi_quad_spi_0_0 || ORIG_REF_NAME==design_1_axi_quad_spi_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/DESD/shooter_project/shooter_project.gen/sources_1/ip/Pmod_JSTK2_0/src/design_1_axi_quad_spi_0_0/design_1_axi_quad_spi_0_0_ooc.xdc

# XDC: c:/DESD/shooter_project/shooter_project.gen/sources_1/ip/Pmod_JSTK2_0/src/design_1_axi_quad_spi_0_0/design_1_axi_quad_spi_0_0_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_axi_quad_spi_0_0 || ORIG_REF_NAME==design_1_axi_quad_spi_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# IP: c:/DESD/shooter_project/shooter_project.srcs/sources_1/ip/Pmod_JSTK2_0/Pmod_JSTK2_0.xci
# IP: The module: 'Pmod_JSTK2_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/DESD/shooter_project/shooter_project.gen/sources_1/ip/Pmod_JSTK2_0/src/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_0_0 || ORIG_REF_NAME==design_1_clk_wiz_0_0} -quiet] -quiet

# IP: c:/DESD/shooter_project/shooter_project.gen/sources_1/ip/Pmod_JSTK2_0/src/design_1_proc_sys_reset_0_0/design_1_proc_sys_reset_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_proc_sys_reset_0_0 || ORIG_REF_NAME==design_1_proc_sys_reset_0_0} -quiet] -quiet

# IP: c:/DESD/shooter_project/shooter_project.gen/sources_1/ip/Pmod_JSTK2_0/src/design_1_axi_quad_spi_0_0/design_1_axi_quad_spi_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_quad_spi_0_0 || ORIG_REF_NAME==design_1_axi_quad_spi_0_0} -quiet] -quiet

# XDC: c:/DESD/shooter_project/shooter_project.gen/sources_1/ip/Pmod_JSTK2_0/src/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_0_0 || ORIG_REF_NAME==design_1_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/DESD/shooter_project/shooter_project.gen/sources_1/ip/Pmod_JSTK2_0/src/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0_ooc.xdc

# XDC: c:/DESD/shooter_project/shooter_project.gen/sources_1/ip/Pmod_JSTK2_0/src/design_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Pmod_JSTK2_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/DESD/shooter_project/shooter_project.gen/sources_1/ip/Pmod_JSTK2_0/src/design_1_proc_sys_reset_0_0/design_1_proc_sys_reset_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_proc_sys_reset_0_0 || ORIG_REF_NAME==design_1_proc_sys_reset_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/DESD/shooter_project/shooter_project.gen/sources_1/ip/Pmod_JSTK2_0/src/design_1_axi_quad_spi_0_0/design_1_axi_quad_spi_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_axi_quad_spi_0_0 || ORIG_REF_NAME==design_1_axi_quad_spi_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/DESD/shooter_project/shooter_project.gen/sources_1/ip/Pmod_JSTK2_0/src/design_1_axi_quad_spi_0_0/design_1_axi_quad_spi_0_0_ooc.xdc

# XDC: c:/DESD/shooter_project/shooter_project.gen/sources_1/ip/Pmod_JSTK2_0/src/design_1_axi_quad_spi_0_0/design_1_axi_quad_spi_0_0_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_axi_quad_spi_0_0 || ORIG_REF_NAME==design_1_axi_quad_spi_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet
