# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/new/pins.xdc

# Block Designs: bd/design_1/design_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_AXI4Stream_UART_0_0/design_1_AXI4Stream_UART_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_AXI4Stream_UART_0_0 || ORIG_REF_NAME==design_1_AXI4Stream_UART_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_AXI4Stream_7Segment_0_0/design_1_AXI4Stream_7Segment_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_AXI4Stream_7Segment_0_0 || ORIG_REF_NAME==design_1_AXI4Stream_7Segment_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_alu_0_0/design_1_alu_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_alu_0_0 || ORIG_REF_NAME==design_1_alu_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_0_0 || ORIG_REF_NAME==design_1_clk_wiz_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_util_vector_logic_0_0/design_1_util_vector_logic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_util_vector_logic_0_0 || ORIG_REF_NAME==design_1_util_vector_logic_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_decoder_0_1/design_1_decoder_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_decoder_0_1 || ORIG_REF_NAME==design_1_decoder_0_1} -quiet] -quiet

# XDC: bd/design_1/design_1_ooc.xdc
