@echo off
REM ****************************************************************************
REM Vivado (TM) v2020.2 (64-bit)
REM
REM Filename    : elaborate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for elaborating the compiled design
REM
REM Generated by Vivado on Sat Sep 11 18:23:30 +0200 2021
REM SW Build 3064766 on Wed Nov 18 09:12:45 MST 2020
REM
REM Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
REM
REM usage: elaborate.bat
REM
REM ****************************************************************************
REM elaborate design
echo "xelab -wto d79a9f4b6a2b474f8d4abba64a4f4880 --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip --snapshot tb_FIFO_behav xil_defaultlib.tb_FIFO -log elaborate.log"
call xelab  -wto d79a9f4b6a2b474f8d4abba64a4f4880 --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip --snapshot tb_FIFO_behav xil_defaultlib.tb_FIFO -log elaborate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
