@echo off
REM ****************************************************************************
REM Vivado (TM) v2020.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Mon Sep 13 10:26:24 +0200 2021
REM SW Build 3064766 on Wed Nov 18 09:12:45 MST 2020
REM
REM Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim tb_ShiftRegister_v0_behav -key {Behavioral:sim_1:Functional:tb_ShiftRegister_v0} -tclbatch tb_ShiftRegister_v0.tcl -view C:/DESD/Projects/LAB0_01_ShiftRegister_project.xpr/LAB0_ShiftRegister_project/LAB0_ShiftRegister_project.srcs/sim_1/new/dut0_tb_ShiftRegister_v0_behav.wcfg -log simulate.log"
call xsim  tb_ShiftRegister_v0_behav -key {Behavioral:sim_1:Functional:tb_ShiftRegister_v0} -tclbatch tb_ShiftRegister_v0.tcl -view C:/DESD/Projects/LAB0_01_ShiftRegister_project.xpr/LAB0_ShiftRegister_project/LAB0_ShiftRegister_project.srcs/sim_1/new/dut0_tb_ShiftRegister_v0_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
