# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/basys3_master_xdc.xdc

# Block Designs: bd/top_bd/top_bd.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_bd || ORIG_REF_NAME==top_bd} -quiet] -quiet

# IP: bd/top_bd/ip/top_bd_debouncer_0_0/top_bd_debouncer_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_bd_debouncer_0_0 || ORIG_REF_NAME==top_bd_debouncer_0_0} -quiet] -quiet

# IP: bd/top_bd/ip/top_bd_AXI4Stream_UART_0_0/top_bd_AXI4Stream_UART_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_bd_AXI4Stream_UART_0_0 || ORIG_REF_NAME==top_bd_AXI4Stream_UART_0_0} -quiet] -quiet

# IP: bd/top_bd/ip/top_bd_axi4stream_data_samp_0_0/top_bd_axi4stream_data_samp_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_bd_axi4stream_data_samp_0_0 || ORIG_REF_NAME==top_bd_axi4stream_data_samp_0_0} -quiet] -quiet

# IP: bd/top_bd/ip/top_bd_axi4stream_data_out_0_0/top_bd_axi4stream_data_out_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_bd_axi4stream_data_out_0_0 || ORIG_REF_NAME==top_bd_axi4stream_data_out_0_0} -quiet] -quiet

# IP: bd/top_bd/ip/top_bd_edge_detector_0_0/top_bd_edge_detector_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_bd_edge_detector_0_0 || ORIG_REF_NAME==top_bd_edge_detector_0_0} -quiet] -quiet

# IP: bd/top_bd/ip/top_bd_util_vector_logic_0_1/top_bd_util_vector_logic_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_bd_util_vector_logic_0_1 || ORIG_REF_NAME==top_bd_util_vector_logic_0_1} -quiet] -quiet

# IP: bd/top_bd/ip/top_bd_clk_wiz_0_1/top_bd_clk_wiz_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_bd_clk_wiz_0_1 || ORIG_REF_NAME==top_bd_clk_wiz_0_1} -quiet] -quiet

# IP: bd/top_bd/ip/top_bd_clk_wiz_0_1_1/top_bd_clk_wiz_0_1.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==top_bd_clk_wiz_0_1 || ORIG_REF_NAME==top_bd_clk_wiz_0_1} -quiet] -quiet

# XDC: bd/top_bd/top_bd_ooc.xdc
