@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Thu Apr 23 18:22:44 +0200 2020
REM SW Build 2708876 on Wed Nov  6 21:40:23 MST 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
echo "xsim tb_KittCarPWM_behav -key {Behavioral:sim_1:Functional:tb_KittCarPWM} -tclbatch tb_KittCarPWM.tcl -view C:/DESD/Project/LAB1 - 02 - KittCar PWM/KittCarPWM/KittCarPWM.srcs/sim_1/imports/KittCarPWM/KittCarPWM.sim/sim_1/behav/tb_KittCarPWM_behav.wcfg -log simulate.log"
call xsim  tb_KittCarPWM_behav -key {Behavioral:sim_1:Functional:tb_KittCarPWM} -tclbatch tb_KittCarPWM.tcl -view C:/DESD/Project/LAB1 - 02 - KittCar PWM/KittCarPWM/KittCarPWM.srcs/sim_1/imports/KittCarPWM/KittCarPWM.sim/sim_1/behav/tb_KittCarPWM_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
