# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/DESD/audio_project/audio_project.srcs/sources_1/bd/audio_bd/ip/audio_bd_pmod_i2s2_0_0/audio_bd_pmod_i2s2_0_0.xci
# IP: The module: 'audio_bd_pmod_i2s2_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/DESD/audio_project/audio_project.gen/sources_1/bd/audio_bd/ip/audio_bd_pmod_i2s2_0_0/src/axis_data_fifo_0/axis_data_fifo_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axis_data_fifo_0 || ORIG_REF_NAME==axis_data_fifo_0} -quiet] -quiet

# IP: c:/DESD/audio_project/audio_project.srcs/sources_1/bd/audio_bd/ip/audio_bd_pmod_i2s2_0_0/audio_bd_pmod_i2s2_0_0.xci
# IP: The module: 'audio_bd_pmod_i2s2_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/DESD/audio_project/audio_project.gen/sources_1/bd/audio_bd/ip/audio_bd_pmod_i2s2_0_0/src/axis_data_fifo_0/axis_data_fifo_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axis_data_fifo_0 || ORIG_REF_NAME==axis_data_fifo_0} -quiet] -quiet
