# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/DESD/Projects/block_adder/block_adder.srcs/sources_1/bd/top_bd/ip/top_bd_AXI4Stream_UART_0_0/top_bd_AXI4Stream_UART_0_0.xci
# IP: The module: 'top_bd_AXI4Stream_UART_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/DESD/Projects/block_adder/block_adder.gen/sources_1/bd/top_bd/ip/top_bd_AXI4Stream_UART_0_0/top_bd_AXI4Stream_UART_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_bd_AXI4Stream_UART_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/DESD/Projects/block_adder/block_adder.srcs/sources_1/bd/top_bd/ip/top_bd_AXI4Stream_UART_0_0/top_bd_AXI4Stream_UART_0_0.xci
# IP: The module: 'top_bd_AXI4Stream_UART_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/DESD/Projects/block_adder/block_adder.gen/sources_1/bd/top_bd/ip/top_bd_AXI4Stream_UART_0_0/top_bd_AXI4Stream_UART_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_bd_AXI4Stream_UART_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
