set_property SRC_FILE_INFO {cfile:/home/mconsonni/Scrivania/DESD/Projects/project_1/project_1.srcs/constrs_1/new/pins.xdc rfile:../../../project_1.srcs/constrs_1/new/pins.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U16 [get_ports LED]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V17 [get_ports SW]
